#########################################################
#      数据连接配置
#########################################################
mysqldb:
  ip: "172.30.111.11"
  port: "3306"
  username: "111"
  password: "特特"
  defaultDB: "特特"
global:
  #excel 路径
  case_path: "case/case_point.xls"
  project_name: "系统"

